name: kitchn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  arcane: ^6.3.0
  arcane_auth: ^1.8.1
  http: ^1.5.0
  html2md: ^1.3.2
  markdown_widget: ^2.3.2+8
  arcane_user: ^1.1.0
  serviced: ^1.0.3
  arcane_fluf: ^1.3.0
  fire_crud: ^3.1.8
  artifact: ^1.0.14
  firebase_core: ^4.1.1
  hive_flutter: ^1.1.0
  firebase_auth: ^6.1.0
  flutter_thumbhash: ^0.1.0+1
  thumbhash: ^0.1.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fire_crud_gen: ^1.0.2
  artifact_gen: ^1.0.15
  build_runner: ^2.5.4
flutter:
  uses-material-design: true
scripts:
  hello: echo hello world!
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  fix_pods: cd macos && rm -rf Podfile.lock && pod install --repo-update