// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3pZ68pGeC4FHcayDDgiYga6frTQhM0sQ',
    appId: '1:1075236772835:web:8d4732f0f6c14af1445ed6',
    messagingSenderId: '1075236772835',
    projectId: 'kitchn-f4cf3',
    authDomain: 'kitchn-f4cf3.firebaseapp.com',
    storageBucket: 'kitchn-f4cf3.firebasestorage.app',
    measurementId: 'G-G14KXFJLXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgteFgqXi5dQ9xxmGYlHAyx_6uhhnIWUE',
    appId: '1:1075236772835:android:142be4a07768e529445ed6',
    messagingSenderId: '1075236772835',
    projectId: 'kitchn-f4cf3',
    storageBucket: 'kitchn-f4cf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANUO4k2MDQ6CtR1d-da2VD5rxmd1grVkE',
    appId: '1:1075236772835:ios:9492759ea1444915445ed6',
    messagingSenderId: '1075236772835',
    projectId: 'kitchn-f4cf3',
    storageBucket: 'kitchn-f4cf3.firebasestorage.app',
    iosBundleId: 'com.example.kitchn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANUO4k2MDQ6CtR1d-da2VD5rxmd1grVkE',
    appId: '1:1075236772835:ios:9492759ea1444915445ed6',
    messagingSenderId: '1075236772835',
    projectId: 'kitchn-f4cf3',
    storageBucket: 'kitchn-f4cf3.firebasestorage.app',
    iosBundleId: 'com.example.kitchn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3pZ68pGeC4FHcayDDgiYga6frTQhM0sQ',
    appId: '1:1075236772835:web:fda393bff3d426a3445ed6',
    messagingSenderId: '1075236772835',
    projectId: 'kitchn-f4cf3',
    authDomain: 'kitchn-f4cf3.firebaseapp.com',
    storageBucket: 'kitchn-f4cf3.firebasestorage.app',
    measurementId: 'G-PGDLDTLE0H',
  );
}
